### PR TITLE
Add lint and fix scripts

### PR DESCRIPTION
**Pull request by jrayback**
I thought these two scripts would be handy. The `lint` script just runs eslint and preittier to look for problems. The `fix` script runs both tools again but tries to fix what it can (option for those who may not have auto-format capabilities available in their IDE).

### CODE REVIEW

**Review by rodolfomiranda — APPROVED** [review]

**Review by rodolfomiranda — APPROVED** [review]

**Review by rodolfomiranda — APPROVED** [review]
LGTM

**Comment by jrayback** [comment]
@rodolfomiranda , can you approve? The PR still seems to require an approving review. Thanks!

**Comment by jrayback** [comment]
Waiting for @pfeairheller or @m00sey to approve.

**Comment by pfeairheller** [comment]
> Waiting for @pfeairheller or @m00sey to approve.

Isn't this a given considering we are the ones with write permission?  Tagging us in Discord and in an issue comment to rush us along I would consider pushy and not at all appreciated.

**Comment by jrayback** [comment]
@pfeairheller , I apologize for being pushy. Please take your time. Regards.

**Review by pfeairheller — APPROVED** [review]

**Pull request merged**
