### PR TITLE
update package dependencies

### LINKED ISSUE #6: `text-encoding` npm package no longer maintained? Do we care?
Please see [here](https://www.npmjs.com/package/text-encoding) and [here](https://github.com/inexorabletash/text-encoding). Package is no longer being maintained. The last commit to the source code was in 2018. Do we care? I can't seem to find any real better alternative (cursory search). Functionality might be, essentially, static and not an issue. Lack of security patching, etc. might be concerning, however.

### LINKED ISSUE #12: Suggest moving off of ecdsa-secp256r1 npm package in favor of @noble/curves
See #7 , this is a similar situation. the [ecdsa-secp256r1](https://www.npmjs.com/package/ecdsa-secp256r1) looks like it hasn't been touched in five years. [@noble/curves](https://www.npmjs.com/package/@noble/curves) is being actively maintained and is audited. A potential issue is that @noble/curves only supports secp256k1. Is this algorithm of acceptable strength to support our use case? If so, I recommend switching to the better maintained, audited package.

### LINKED ISSUE #13: `urlsafe-base64` package vs. built-in node.js Buffer.from() and buf.toString() with 'base64url' flag?
Is there something special with the `urlsafe-base64` npm package that we're using it instead of the built-in node.js capability? I've confirmed that all tests pass without the package.

### PR DESCRIPTION
**Pull request by jrayback**
Eliminates sketchy packages:
-  `text-encoding` (remove)
-  `urlsafe-base64` (remove in favor of native node.js capability)
-  `ecdsa-secp256r1` (replace with `@noble/curves`)
fixes #6 
fixes #12 
fixes #13

### CODE REVIEW

**Comment by jrayback** [comment]
The only dependencies we have now are the two maintained/audited @noble packages and the libsodium package.

**Review by AlexAndrei98 — APPROVED** [review]

**Comment by pfeairheller** [comment]
If you are removing the urlsafe-base64 in favor of Node native calls are you pinning this library to be Node only?  Meaning will it no longer be available for Browsers?

**Comment by kentbull** [comment]
That was my question as well. Will the `Buffer.from(<string value> ,'base64url')` and `Buffer.from([<buffer raw val>]).toString('base64url')` syntax work only in Node or does that work with browsers as well?

**Comment by AlexAndrei98** [comment]
One thing I noticed is that in signify we do the [following](https://github.com/WebOfTrust/signify-ts/blob/development/src/buffer-polyfill.ts)
```
import { Buffer } from 'buffer';

try {
    window.Buffer = Buffer;
} catch (e) {}
```

Currently trying to refactor signify to use cesr-ts but It will probably take me the weekend!

**Comment by jrayback** [comment]
Yes, @AlexAndrei98 , and the Node.js docs explicitly suggest `import { Buffer } from 'node.buffer'` for precisely this reason, I imagine (disambiguation). Let me look further into this. I'll make a commit to this PR containing a better approach.

**Comment by jrayback** [comment]
Looks like the import statement @AlexAndrei98 quotes above references the `buffer` npm package [here](https://www.npmjs.com/package/buffer). This package makes the buffer module from node.js available in browsers. The project seems well-maintained and very widely used. Also, it appears that we're already using it in `signify.ts`. I'll see if I can rework this PR to leverage this package rather than reverting to `urlsafe-base64`. Please advise if any objections to this approach.

**Comment by jrayback** [comment]
OK. Using the `buffer` npm package now. This will make the functionality of the native node.js module available widely in browsers. @pfeairheller , I think we're all set to merge this now.

**Comment by jrayback** [comment]
fixes #7

**Review by pfeairheller — APPROVED** [review]

**Pull request merged**
